name: Build and Push Docker Image

on:
  push:
    paths:
      - 'loco-cli.dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: loco-cli.dockerfile
          push: true
          tags: dinosath/loco-cli:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}