name: Build and Push Docker Image

on:
  push:
    paths:
      - 'loco-cli.dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: loco-cli.dockerfile
          push: true
          tags: ghcr.io/dinosath/terakube/loco-cli:1.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}